name: Generate DynX List For AdguardHome and NginX and Reload nginx

on:
  push:
    branches:
      - main
    paths:
      - DynX-AntiBan-list.lst

jobs:
  update-and-restart:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate DynX List and Update Adguard File for first tunnel antiban server
        run: |
          awk -F'\\^' '{print "||"$1"^$dnsrewrite=10.70.95.162"}' DynX-AntiBan-list.lst > other/AdguardHomeReWrite-Tunnel1.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add other/AdguardHomeReWrite-Tunnel1.txt
          git commit -m "Update AdguardHomeReWrite-Tunnel1 with latest domains"
          git push

      - name: Generate DynX List and Update Adguard File for second tunnel antiban server
        run: |
          awk -F'\\^' '{print "||"$1"^$dnsrewrite=10.70.95.150"}' DynX-AntiBan-list.lst > other/AdguardHomeReWrite-Tunnel2.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add other/AdguardHomeReWrite-Tunnel2.txt
          git commit -m "Update AdguardHomeReWrite-Tunnel2 with latest domains"
          git push

      - name: Generate allowed_domains.conf from DynX-AntiBan-list.lst For NginX
        run: |
          echo "map \$ssl_preread_server_name \$allowed_domain {" > other/allowed_domains.conf
          echo "    default 0.0.0.0:0;" >> other/allowed_domains.conf
          while IFS= read -r line; do
            domain=$(echo "$line" | cut -d'^' -f1)
            echo "    ~^(.*\.)?$domain \$ssl_preread_server_name;" >> other/allowed_domains.conf
          done < DynX-AntiBan-list.lst
          echo "}" >> other/allowed_domains.conf
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add other/allowed_domains.conf
          git commit -m "Update allowed_domains.conf with latest domains"
          git push

      - name: Update allowed_domains.conf on server and Reload Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: '${{ secrets.SERVER_IP }}'
          username: '${{ secrets.SSH_USERNAME }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          port: '${{ secrets.SSH_PORT }}'
          script: |
            wget -q https://github.com/MrDevAnony/DynX-AntiBan-Domains/raw/refs/heads/main/other/allowed_domains.conf -O /etc/nginx/allowed_domains.conf
            nginx -t && systemctl reload nginx
            exit

      - name: Update list and clear cashe in AdguardHome
        run: |
          sleep 5
          ${{ secrets.CMD }}
