name: Update DynX List and Restart Container

on:
    push:
        branches:
            - main
        paths:
            - DynX-AntiBan-list.lst

jobs:
    update-and-restart:
        if: github.event_name == 'push' || (github.event.pull_request.merged == true)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Remove filtered domains in Iran (Optimized)
              run: |
                  set -euo pipefail

                  dns_server="5.198.178.208"
                  file="DynX-AntiBan-list.lst"
                  banned_ips=(
                    "10.10.34.34"
                    "2001:4188:2:600:10:10:34:34"
                    "10.10.34.35"
                    "10.10.34.36"
                    "2001:4188:2:600:10:10:34:35"
                    "2001:4188:2:600:10:10:34:36"
                  )
                  tmpfile=$(mktemp)

                  # Create regex pattern for banned IPs
                  pattern=$(IFS="|"; echo "${banned_ips[*]/#/^}" | sed 's/\./\\./g; s/:/:/g')

                  while IFS= read -r domain || [[ -n "$domain" ]]; do
                    domain=$(echo "$domain" | awk -F'^' '{print $1}' | xargs | tr '[:upper:]' '[:lower:]')
                    if [[ -z "$domain" || "$domain" =~ ^# ]]; then
                      echo "Skipping invalid line: ${domain:-<empty>}"
                      continue
                    fi

                    echo "Checking $domain..."
                    
                    resolved=$(dig @$dns_server +time=2 +tries=2 +short "$domain" A "$domain" AAAA 2>&1 | grep -vE "^(;;|$)")

                    if [[ -n "$resolved" ]] && grep -qE "($pattern)" <<< "$resolved"; then
                      echo "❌ Removed: $domain (Banned IP detected)"
                    else
                      echo "✅ Approved: $domain"
                      echo "$domain" >> "$tmpfile"
                    fi
                  done < "$file"

                  if ! diff -q "$tmpfile" "$file" >/dev/null; then
                    mv -f "$tmpfile" "$file"
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"
                    git add "$file"
                    git commit -m "Automated update: Remove banned domains" || echo "No changes to commit"
                  else
                    echo "ℹ️ No changes detected - Skipping commit"
                    rm -f "$tmpfile"
                  fi

            - name: Generate Adguard Files
              run: |
                  set -eo pipefail

                  # Pull latest changes if any
                  git pull origin main || true

                  # Generate Tunnel File
                  awk -F'^' '{print "||"$1"^$dnsrewrite=5.198.178.208"}' DynX-AntiBan-list.lst > AdguardHomeReWrite-Tunnel.txt

                  # Generate Main File
                  awk -F'^' '{print "||"$1"^$dnsrewrite=104.237.250.13"}' DynX-AntiBan-list.lst > AdguardHomeReWrite.txt

                  # Commit changes
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add AdguardHomeReWrite*
                  git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update Adguard rules"
                  git push

            - name: Restart Docker Container
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: "${{ secrets.SERVER_IP }}"
                  username: "${{ secrets.SSH_USERNAME }}"
                  password: "${{ secrets.SSH_PASSWORD }}"
                  port: "${{ secrets.SSH_PORT || 22 }}"
                  script: |
                      rm -f DynX-AntiBan-list.lst

                      wget -q https://github.com/MrDevAnony/DynX-AntiBan-Domains/raw/refs/heads/main/DynX-AntiBan-list.lst

                      docker compose restart

                      exit
